/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProgramaRouteImport } from './routes/programa'
import { Route as InscripcionesRouteImport } from './routes/inscripciones'
import { Route as EdicionesRouteImport } from './routes/ediciones'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramaRoute = ProgramaRouteImport.update({
  id: '/programa',
  path: '/programa',
  getParentRoute: () => rootRouteImport,
} as any)
const InscripcionesRoute = InscripcionesRouteImport.update({
  id: '/inscripciones',
  path: '/inscripciones',
  getParentRoute: () => rootRouteImport,
} as any)
const EdicionesRoute = EdicionesRouteImport.update({
  id: '/ediciones',
  path: '/ediciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/ediciones': typeof EdicionesRoute
  '/inscripciones': typeof InscripcionesRoute
  '/programa': typeof ProgramaRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/ediciones': typeof EdicionesRoute
  '/inscripciones': typeof InscripcionesRoute
  '/programa': typeof ProgramaRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/ediciones': typeof EdicionesRoute
  '/inscripciones': typeof InscripcionesRoute
  '/programa': typeof ProgramaRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/ediciones'
    | '/inscripciones'
    | '/programa'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/ediciones'
    | '/inscripciones'
    | '/programa'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/ediciones'
    | '/inscripciones'
    | '/programa'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  EdicionesRoute: typeof EdicionesRoute
  InscripcionesRoute: typeof InscripcionesRoute
  ProgramaRoute: typeof ProgramaRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programa': {
      id: '/programa'
      path: '/programa'
      fullPath: '/programa'
      preLoaderRoute: typeof ProgramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscripciones': {
      id: '/inscripciones'
      path: '/inscripciones'
      fullPath: '/inscripciones'
      preLoaderRoute: typeof InscripcionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ediciones': {
      id: '/ediciones'
      path: '/ediciones'
      fullPath: '/ediciones'
      preLoaderRoute: typeof EdicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  EdicionesRoute: EdicionesRoute,
  InscripcionesRoute: InscripcionesRoute,
  ProgramaRoute: ProgramaRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
